### ISSUE TITLE
Confirmed availability at Kernel version 4.9+

### ISSUE THREAD

**Issue by ghost** [diederikdehaas/rtl8814AU#6] opened 2017-07-06 23:37 UTC
Just tried to install this driver on my computer using Solus. Strangely enough, it worked without any major errors or bugs.

**Comment by diederikdehaas** [comment] 2021-04-29 22:56
That's awesome :+1: 
And not a bug, thus closing.

**Closed as completed by diederikdehaas** 2021-04-29 22:56 UTC
